### ISSUE TITLE
请教一下，我这里下载整包安装后版本号不更新呢？

### ISSUE THREAD

**Issue by hairui-Zhang** [SilurianYang/uni-app-tools#3]
版本号不更新，重启后还是会再次下载，然后就一直循环了，望指点

**Comment by SilurianYang** [comment]
> 版本号不更新，重启后还是会再次下载，然后就一直循环了，望指点

更新后重新还是更新。一般原因都是你在制作升级包时manifest.json 版本应用版本名称和你update.json中的version节点对不上而导致的
