### ISSUE TITLE
uni-sample-router设置了路由守卫，先进入了一个页面之后再跳转到一个页面

### ISSUE THREAD

**Issue by ManyYearsLater** [SilurianYang/uni-app-tools#4]
作者这个场景能否优化下

**Comment by SilurianYang** [comment]
## 相关问题请在这边提

### 先进入页面再跳转是你用了非$Router的api，$Router无法捕捉。相关表现在原生tabbar，首次进入页面，uni api路由跳转。

#### [直通车](https://github.com/SilurianYang/uni-simple-router/issues)
