### ISSUE TITLE
uni-app-request ajax方法，设置全局响应后拦截beforeFinish时，无法拦截statusCode为200以外的其他情况

### ISSUE THREAD

**Issue by fairangel** [SilurianYang/uni-app-tools#5]
问题：ajax方法，设置全局响应后拦截beforeFinish时，无法拦截statusCode为200以外的其他情况
文件：request.js
行数：123
问题代码：
```
if (statusCode == 200) {
	 verifyRes=await this.defaultReq.beforeFinish(callData);
	if(verifyRes!==undefined){
		resolve(verifyRes);
	}else{
		reject('beforeFinish 钩子必须要有返回结果')
	}
}
```
只有在statesCode等于200时才会触发beforeFinish。其他情况，比如401之类的接口返回的授权状态就无法在beforeFinish拦截器里处理了

**Comment by SilurianYang** [comment]
@fairangel  很抱歉！这个是我的过失，后续会进行修改。最近所有的重心都放在 [uni-simple-router](https://github.com/SilurianYang/uni-simple-router) 上了。如果你急着用可以自行修改下。

**Comment by fairangel** [comment]
:) 客气了，感谢您能分享这样方便的工具集，我也收益颇多

**Comment by SilurianYang** [comment]
## 已经更新了新的生命钩子 如果需要 可查看文档
