### ISSUE TITLE
Vue.prototype定义的变量在微信小程序里获取不到？

### ISSUE THREAD

**Issue by gongph** [SilurianYang/uni-app-tools#6]
Hi, @SilurianYang 在 main.js 中自定义了一些变量，如：
```js
Vue.prototype.imgUrl= 'xxx'
```
运行到微信小程序中 imgUrl = undefined 获取不到？
图片路径输入如下：
```
<image src="http://abc.com/static/undefined/test.png"></image>

**Comment by SilurianYang** [comment]
请使用一些不被覆盖的变量名  并使用双向绑定进行读取

**Comment by gongph** [comment]
> 请使用一些不被覆盖的变量名 并使用双向绑定进行读取

大佬，你的意思是上面那种做法确实获取不到是吗？ 必须在 data 中重新赋值？例如：

```html
<script>
export default {
  ...
  data () {
    return {
      imageUrl: this.imgUrl
    }
  }
}
</script>
```

**Comment by SilurianYang** [comment]
`uni-app`  在编译成小程序时 并不是把h5所有的功能都移过去的、只是把语法编译成小程序的那套。所以 你应该编写成小程序支持的语法才可以。

**Comment by gongph** [comment]
> `uni-app` 在编译成小程序时 并不是把h5所有的功能都移过去的、只是把语法编译成小程序的那套。所以 你应该编写成小程序支持的语法才可以。

那传统你们的做法是怎样的呢？请问一下。我看您main.js 中 Vue.prototype 上也定义了很多变量

**Comment by SilurianYang** [comment]
看起来你的写法是没有问题  你可以截图怎么在template 使用的吗？ 或者你把 `imgUrl` 换成其他的  比如`xxxxximgUrl`  试试

**Comment by gongph** [comment]
> 看起来你的写法是没有问题 你可以截图怎么在template 使用的吗？ 或者你把 `imgUrl` 换成其他的 比如`xxxxximgUrl` 试试

谢谢你的回复。放在 data 中是没有问题的。就想知道为什么放在 Vue.prototype 上为什么取不到值

**Comment by lyysss** [comment]
> > 看起来你的写法是没有问题你可以截图怎么在模板使用的吗？或者你把`imgUrl`换成其他的`xxxxximgUrl`比如试试
> 
> 谢谢你的回复。放在数据中是没有问题的。就想知道为什么放在Vue.prototype上为什么取不到值

请问一下问题解决了吗 我也遇到一样的情况的。
